<?php
	//phpinfo();
	echo "RUN THIS ONCE ONLY!";
	die;
	require("station.php");
	$con = mysqli_connect("localhost","root","temppassword123!","maindb");
	if (mysqli_connect_errno($con)) {
		echo "Failed to connect to MySQL: " . mysqli_connect_error();
	}
	
	$arr = array(
		"Jurong East",
		"Bukit Batok",
		"Bukit Gombak",
		"Choa Chu Kang",
		"Yew Tee",
		"Sungei Kadut",
		"Kranji",
		"Marsiling",
		"Woodlands",
		"Admiralty",
		"Sembawang",
		"Canberra",
		"Yishun",
		"Khatib",
		"Yio Chu Kang",
		"Ang Mo Kio",
		"Bishan",
		"Braddell",
		"Toa Payoh",
		"Novena",
		"Newton",
		"Orchard",
		"Somerset",
		"Dhoby Ghaut",
		"City Hall",
		"Raffles Place",
		"Marina Bay",
		"Marina South Pier",
		"Pasir Ris",
		"Tampines",
		"Simei",
		"Tanah Merah",
		"Bedok",
		"Kembangan",
		"Eunos",
		"Paya Lebar",
		"Aljunied",
		"Kallang",
		"Lavender",
		"Bugis",
		"City Hall",
		"Raffles Place",
		"Tanjong Pagar",
		"Outram Park",
		"Tiong Bahru",
		"Redhill",
		"Queenstown",
		"Commonwealth",
		"Buona Vista",
		"Dover",
		"Clementi",
		"Jurong East",
		"Chinese Garden",
		"Lakeside",
		"Boon Lay",
		"Pioneer",
		"Joo Koon",
		"Gul Circle",
		"Tuas Crescent",
		"Tuas West Road",
		"Tuas Link",
		"Expo",
		"Changi Airport",
		"HarbourFront",
		"Keppel",
		"Outram Park",
		"Chinatown",
		"Clarke Quay",
		"Dhoby Ghaut",
		"Little India",
		"Farrer Park",
		"Boon Keng",
		"Potong Pasir",
		"Woodleigh",
		"Serangoon",
		"Kovan",
		"Hougang",
		"Buangkok",
		"Sengkang",
		"Punggol",
		"Dhoby Ghaut",
		"Bras Basah",
		"Esplanade",
		"Promenade",
		"Nicoll Highway",
		"Stadium",
		"Mountbatten",
		"Dakota",
		"Paya Lebar",
		"MacPherson",
		"Tai Seng",
		"Bartley",
		"Serangoon",
		"Lorong Chuan",
		"Bishan",
		"Marymount",
		"Caldecott",
		"Bukit Brown",
		"Botanic Gardens",
		"Farrer Road",
		"Holland Village",
		"Buona Vista",
		"one-north",
		"Kent Ridge",
		"Haw Par Villa",
		"Pasir Panjang",
		"Labrador Park",
		"Telok Blangah",
		"HarbourFront",
		"Bayfront",
		"Marina Bay",
		"Bukit Panjang",
		"Cashew",
		"Hillview",
		"Hume Avenue",
		"Beauty World",
		"King Albert Park",
		"Sixth Avenue",
		"Tan Kah Kee",
		"Botanic Gardens",
		"Stevens",
		"Newton",
		"Little India",
		"Rochor",
		"Bugis",
		"Promenade",
		"Bayfront",
		"Downtown",
		"Telok Ayer",
		"Chinatown",
		"Fort Canning",
		"Bencoolen",
		"Jalan Besar",
		"Bendemeer",
		"Geylang Bahru",
		"Mattar",
		"MacPherson",
		"Ubi",
		"Kaki Bukit",
		"Bedok North",
		"Bedok Reservoir",
		"Tampines West",
		"Tampines",
		"Tampines East",
		"Upper Changi",
		"Expo",
		"Woodlands North",
		"Woodlands",
		"Woodlands South",
		"Springleaf",
		"Lentor",
		"Mayflower",
		"Bright Hill",
		"Upper Thomson",
		"Caldecott",
		"Mount Pleasant",
		"Stevens",
		"Napier",
		"Orchard Boulevard",
		"Orchard",
		"Great World",
		"Havelock",
		"Outram Park",
		"Maxwell",
		"Shenton Way",
		"Marina Bay",
		"Marina South",
		"Gardens by the Bay"
		);
		$h = 0;
	foreach ($arr as &$station) {
		
		$rand = rand(1,100);
		for($i = 0; $i < $rand; $i++) {
			$rand2 = rand(0,100);
			if ($rand2 < 75) {
				$rand2 = 1;
			} else {
				$rand2 = 0;
			}
			echo "<br />Doing " . $h . " out of " . count($arr) . " | Iteration: ".$i." out of ".$rand2;
			$sql = "INSERT INTO `responses` VALUES (NULL, NULL, '".$station."',". $rand2 .",NULL);";
			$result = mysqli_query($con, $sql);
		}
		$h++;
	}
	echo "Done";
?>
